#ifndef LIBASCENDCXX_INCLUDE_ASCEND_STD___NUMERIC_GCD_H_
#define LIBASCENDCXX_INCLUDE_ASCEND_STD___NUMERIC_GCD_H_

#include "ascend/std/__numeric/gcd_lcm.h"

#endif  // LIBASCENDCXX_INCLUDE_ASCEND_STD___NUMERIC_GCD_H_
