#ifndef LIBASCENDCXX_INCLUDE_ASCEND_STD___ALGORITHM_SWAP_H_
#define LIBASCENDCXX_INCLUDE_ASCEND_STD___ALGORITHM_SWAP_H_

#include "ascend/std/__utility/swap.h"

#endif  // LIBASCENDCXX_INCLUDE_ASCEND_STD___ALGORITHM_SWAP_H_
